name: CompileForLadder
on:
  workflow_call:

jobs:
  build_ladder_binary:
    name: Compile Cython for Ladder

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ '3.11' ]

    steps:
      # check-out repo
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      # install poetry
      - name: Install poetry
        run: pipx install poetry
      # set-up python with cache
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'
      # Install requirements and build extension
      - name: Install requirements and build extension
        run: |
          poetry install --with dev
      - uses: actions/upload-artifact@v4
        with:
          name: ladder_binary
          path: |
            cython_extensions/*.so
