name: Orchestrator

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  call-testing-pipeline:
    name: Testing
    uses: ./.github/workflows/test.yml

  version-bump:
    name: VersionBump
    needs: call-testing-pipeline
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.get_tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
      - name: Show current commit
        run: |
          git log -1
          echo "GITHUB_SHA: $GITHUB_SHA"
          echo "git rev-parse HEAD: $(git rev-parse HEAD)"
      - name: Run semantic-release (version only)
        run: |
          pip install python-semantic-release==9.15.2
          semantic-release version --no-push -vv
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN_TEST }}
      - name: Show version changes
        run: |
          git status
          git diff pyproject.toml
          cat pyproject.toml
      - name: Push tags and commits
        run: |
          git push origin HEAD
          git push origin --tags
      - name: Wait for tag to be available
        run: |
          TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          for i in {1..10}; do
            git fetch --tags
            git rev-parse "refs/tags/$TAG" && exit 0
            sleep 2
          done
          echo "Tag $TAG not found after waiting."
          exit 1
      - name: Get latest tag
        id: get_tag
        run: echo "tag=$(git describe --tags $(git rev-list --tags --max-count=1))" >> $GITHUB_OUTPUT

  call-compiling-pipeline:
    name: CompileCython
    needs: version-bump
    uses: ./.github/workflows/compile_cython.yml

  call-wheels-pipeline:
    name: Wheels
    needs:
      - version-bump
      - call-compiling-pipeline
    uses: ./.github/workflows/wheels.yml
    with:
      tag: ${{ needs.version-bump.outputs.tag }}
    secrets: inherit

  call-release-pipeline:
    name: Release
    needs:
      - version-bump
      - call-compiling-pipeline
      - call-wheels-pipeline
    uses: ./.github/workflows/release.yml
    with:
      tag: ${{ needs.version-bump.outputs.tag }}
    secrets: inherit
